restart_file: .na
start_datetime: 2022-03-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-04-01 00:00:00
forecast_horizon: 0.0
sim_name: pf_test
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: false
