restart_file: .na
start_datetime: 2023-10-10 00:00:00
end_datetime: .na
forecast_start_datetime: 2023-10-14 00:00:00
forecast_horizon: 35
sim_name: glm_aed_v1
configure_flare: configure_flare_glm_aed.yml
configure_obs: observation_processing.yml
use_s3: TRUE
