restart_file: .na
start_datetime: 2022-07-22 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-07-25 00:00:00
forecast_horizon: 16
sim_name: test_run
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: FALSE
