s3:
  drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/met
  inflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/inflow
  outflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/outflow
  targets:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/targets
  forecasts:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  warm_start:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
  site_id: fcre
  name: Falling Creek Reservoir
  latitude: 37.307
  longitude: -79.837
da_setup:
  da_method: enkf
  par_fit_method: perturb
  ensemble_size: 200
  localization_distance: .na
  pf_always_resample: no
  no_negative_states: yes
  assimilate_first_step: no
  use_obs_constraint: yes
  inflation_factor: 1.0
model_settings:
  ncore: 10
  max_model_layers: 75
  model_name: glm_aed
  base_GLM_nml: glm3.nml
  base_AED_nml: aed2_3groups.nml
  base_AED_phyto_pars_nml: aed_phyto_pars_3groups.csv
  base_AED_zoop_pars_nml: aed2_zoop_pars.nml
  modeled_depths:
  - 0.00
  - 1.00
  - 1.50
  - 2.00
  - 3.00
  - 4.00
  - 5.00
  - 6.00
  - 7.00
  - 8.00
  - 9.00
  par_config_file: parameter_calibration_config_aed_3groups.csv
  obs_config_file: observations_config_aed_manual.csv
  states_config_file: states_config_aed_3groups_manual.csv
  depth_model_sd_config_file: depth_model_sd_aed.csv
default_init:
  lake_depth: 9.4
  temp:
  - 25.667
  - 24.9101
  - 23.067
  - 21.8815
  - 19.6658
  - 16.5739
  - 12.9292
  - 12.8456
  - 12.8127
  - 12.8079
  - 12.778
  temp_depths:
  - 0.127
  - 1.004
  - 2.005
  - 3.021
  - 4.002
  - 5.004
  - 6.004
  - 7.01
  - 8.001
  - 9.015
  - 9.518
  salinity: 0.0
  snow_thickness: 0.0
  white_ice_thickness: 0.0
  blue_ice_thickness: 0.0
flows:
   include_inflow: TRUE
   include_outflow: TRUE
   future_inflow_model: future/model_id=historical_interp
   historical_inflow_model: historical/model_id=historical_interp
   local_inflow_directory: drivers/inflow
   future_outflow_model: future/model_id=historical_interp
   historical_outflow_model: historical/model_id=historical_interp
   local_outflow_directory: drivers/outflow
   use_ler_vars: FALSE
met:
   future_met_model: gefs-v12/stage2
   future_met_use_s3: TRUE
   historical_met_use_s3: FALSE
   forecast_lag_days: 0
   historical_met_model: historical/model_id=obs_interp # or historical_met_model: gets-v12/stage3
   local_met_directory: drivers/met
   use_ler_vars: FALSE
   use_openmeteo: FALSE
uncertainty:
  observation: yes
  process: yes
  weather: yes
  initial_condition: yes
  parameter: yes
  inflow: yes
output_settings:
  diagnostics_names:
  - extc
