restart_file: .na
start_datetime: 2021-01-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-12-31 00:00:00
forecast_horizon: 0.0
sim_name: pf_test_aed
configure_flare: configure_flare_glm_aed_3groups_manual.yml
configure_obs: observation_processing.yml
use_s3: no
