file_path:
  qaqc_data_directory: .na
  noaa_directory: .na
  inflow_directory: .na
  configuration_directory: .na
  execute_directory: .na
  forecast_output_directory: .na
  run_config: .na
s3:
  drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/met/gefs-v12
  inflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/inflow/fcre/lm_ar
  targets:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/targets
  forecasts:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  warm_start:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
  site_id: fcre
  name: Falling Creek Reservoir
  latitude: 37.307
  longitude: -79.837
da_setup:
  da_method: enkf
  par_fit_method: perturb
  ensemble_size: 100
  localization_distance: .na
  no_negative_states: yes
  assimilate_first_step: no
  use_obs_constraint: yes
  inflation_factor: 1.0
model_settings:
  ncore: 4
  model_name: glm_aed
  base_GLM_nml: glm3.nml
  base_AED_nml: aed2_3groups.nml
  base_AED_phyto_pars_nml: aed_phyto_pars_3groups.csv
  base_AED_zoop_pars_nml: aed2_zoop_pars.nml
  modeled_depths:
  - 0.00
  - 0.50
  - 1.00
  - 1.50
  - 2.00
  - 2.50
  - 3.00
  - 3.50
  - 4.00
  - 4.50
  - 5.00
  - 5.50
  - 6.00
  - 6.50
  - 7.00
  - 7.50
  - 8.00
  - 8.50
  - 9.00

  par_config_file: parameter_calibration_config_aed_3groups.csv
  obs_config_file: observations_config_aed_manual.csv
  states_config_file: states_config_aed_3groups_manual.csv
  depth_model_sd_config_file: depth_model_sd_aed.csv
default_init:
  lake_depth: 9.4
  temp:
  - 25.667
  - 24.9101
  - 23.067
  - 21.8815
  - 19.6658
  - 16.5739
  - 12.9292
  - 12.8456
  - 12.8127
  - 12.8079
  - 12.778
  temp_depths:
  - 0.127
  - 1.004
  - 2.005
  - 3.021
  - 4.002
  - 5.004
  - 6.004
  - 7.01
  - 8.001
  - 9.015
  - 9.518
  salinity: 0.0
  snow_thickness: 0.0
  white_ice_thickness: 0.0
  blue_ice_thickness: 0.0
inflow:
  use_forecasted_inflow: FALSE
met:
  use_forecasted_met: FALSE
uncertainty:
  observation: yes
  process: yes
  weather: yes
  initial_condition: yes
  parameter: yes
  met_downscale: yes
  inflow_process: yes
output_settings:
  diagnostics_names:
  - extc
  - PHY_green_fPho
  - PHY_green_fT
  - PHY_green_fNit
  - PHY_cyano_fPho
  - PHY_cyano_fT
  - PHY_cyano_fNit
  - PHY_diatom_fPho
  - PHY_diatom_fT
  - PHY_diatom_fNit
  - PHY_par
  - PHY_upt_dic
  - PHY_upt_po4
  - PHY_upt_n2
  - PHY_upt_nh4
  - PHY_upt_no3
