file_path:
   qaqc_data_directory: .na
   noaa_directory: .na
   inflow_directory: .na
   configuration_directory: .na
   execute_directory: .na
   forecast_output_directory: .na
s3:
  drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/met
  inflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/inflow/fcre/lm_ar
  outflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/outflow/fcre/lm_ar
  targets:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/targets
  forecasts:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  restart:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
   site_id: fcre
   name: Falling Creek Reservoir
   latitude: 37.307   #Degrees North
   longitude: -79.837  #Degrees East
metadata:
   generate_eml: TRUE
   forecast_project_id: test
   abstract: "This is where a longer description of the forecast can be added"
   forecast_title: FLARE
   intellectualRights: MIT
   model_description:
      forecast_model_id: https://github.com/rqthomas/flare/commit/d1ddcb07b9d28863890597503fc4aa4a4496de56
      name: General Lake Model
      type: process-based
      repository: https://github.com/AquaticEcoDynamics/GLM/releases/tag/v3.1.0
   me:
      individualName:
         givenName: "Quinn"
         surName: "Thomas"
      electronicMailAddress:  "INSERT"
      id: INSERT ORCID
da_setup:
    da_method: enkf
    par_fit_method: perturb_const
    ensemble_size:  256
    localization_distance: .na #distance in meters were covariances in the model error are used
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
    obs_filename: fcre-targets-insitu.csv
model_settings:
   ncore: 4
   model_name: glm
   base_GLM_nml: glm3.nml
   max_model_layers: 100
   modeled_depths: [0.00,1.00,1.50,2.00,3.00,4.00,5.00,6.00,7.00,8.00,9.00]
   par_config_file: parameter_calibration_config.csv
   obs_config_file: observations_config.csv
   states_config_file: states_config.csv
   depth_model_sd_config_file: depth_model_sd.csv
default_init:
   lake_depth: 9.4  #not a modeled state
   temp: [25.667, 24.9101, 23.067, 21.8815, 19.6658, 16.5739, 12.9292, 12.8456, 12.8127, 12.8079, 12.778]
   temp_depths: [0.127, 1.004, 2.005, 3.021, 4.002, 5.004, 6.004, 7.01, 8.001, 9.015, 9.518]
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
flows:
   include_inflow: TRUE
   include_outflow: TRUE
   historical_inflow_model: historic/model_id=inflow-xbgoost/site_id={site_id}
   future_inflow_model: future/model_id=inflow-xbgoost/reference_datetime={reference_date}/site_id={site_id}
   historical_outflow_model: historic/model_id=inflow-xbgoost/site_id={site_id}
   future_outflow_model: future/model_id=inflow-xbgoost/reference_datetime={reference_date}/site_id={site_id}
   local_inflow_directory: drivers/inflow
   local_outflow_directory: drivers/outflow
   use_flows_s3: no
   use_ler_vars: no
met:
   future_met_model: 'gefs-v12/stage2/reference_datetime={reference_date}/site_id={site_id}'
   historical_met_model: 'gefs-v12/stage3/site_id={site_id}'
   historical_met_use_s3: TRUE
   future_met_use_s3: TRUE
   use_openmeteo: FALSE
   local_met_directory: 'drivers'
   use_forecasted_met: TRUE
   use_ler_vars: FALSE
   forecast_lag_days: 1
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow: TRUE
output_settings:
   diagnostics_names:  [extc]
   evaluate_past: FALSE
   variables_in_scores: [state, parameter]
   generate_plots: FALSE
   diagnostics_daily:
      names: ['Tot Inflow Vol', 'Tot Outflow Vol', 'Overflow Vol', 'temp']
      save_names: ['inflow', 'outflow','overflow', 'temp_outflow']
      file: ['lake.csv', 'lake.csv','lake.csv', 'outlet_00.csv']
      depth: [NA, NA, NA, NA]
