on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"

name: defaultV2

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.3.2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: install deps
#        shell: Rscript {0}
#        run: |
#          remotes::install_github("FLARE-forecast/FLAREr")

# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:  Rscript $GITHUB_WORKSPACE/workflows/defaultV2/combined_forecast.R
